// all the midi statuses dictionary
export const messageTypes = {
    noteOff: 0x80,
    noteOn: 0x90,
    polyPressure: 0xa0,
    controllerChange: 0xb0,
    programChange: 0xc0,
    channelPressure: 0xd0,
    pitchBend: 0xe0,
    systemExclusive: 0xf0,
    timecode: 0xf1,
    songPosition: 0xf2,
    songSelect: 0xf3,
    tuneRequest: 0xf6,
    clock: 0xf8,
    start: 0xfa,
    continue: 0xfb,
    stop: 0xfc,
    activeSensing: 0xfe,
    reset: 0xff,
    sequenceNumber: 0x00,
    text: 0x01,
    copyright: 0x02,
    trackName: 0x03,
    instrumentName: 0x04,
    lyric: 0x05,
    marker: 0x06,
    cuePoint: 0x07,
    programName: 0x08,
    midiChannelPrefix: 0x20,
    midiPort: 0x21,
    endOfTrack: 0x2f,
    setTempo: 0x51,
    smpteOffset: 0x54,
    timeSignature: 0x58,
    keySignature: 0x59,
    sequenceSpecific: 0x7f
} as const;

export type messageTypes = (typeof messageTypes)[keyof typeof messageTypes];

// all midi controllers dictionary
export const midiControllers = {
    bankSelect: 0,
    modulationWheel: 1,
    breathController: 2,
    footController: 4,
    portamentoTime: 5,
    dataEntryMsb: 6,
    mainVolume: 7,
    balance: 8,
    pan: 10,
    expressionController: 11,
    effectControl1: 12,
    effectControl2: 13,
    generalPurposeController1: 16,
    generalPurposeController2: 17,
    generalPurposeController3: 18,
    generalPurposeController4: 19,
    lsbForControl0BankSelect: 32,
    lsbForControl1ModulationWheel: 33,
    lsbForControl2BreathController: 34,
    lsbForControl4FootController: 36,
    lsbForControl5PortamentoTime: 37,
    lsbForControl6DataEntry: 38,
    lsbForControl7MainVolume: 39,
    lsbForControl8Balance: 40,
    lsbForControl10Pan: 42,
    lsbForControl11ExpressionController: 43,
    lsbForControl12EffectControl1: 44,
    lsbForControl13EffectControl2: 45,
    sustainPedal: 64,
    portamentoOnOff: 65,
    sostenutoPedal: 66,
    softPedal: 67,
    legatoFootswitch: 68,
    hold2Pedal: 69,
    soundVariation: 70,
    filterResonance: 71,
    releaseTime: 72,
    attackTime: 73,
    brightness: 74,
    decayTime: 75,
    vibratoRate: 76,
    vibratoDepth: 77,
    vibratoDelay: 78,
    soundController10: 79,
    generalPurposeController5: 80,
    generalPurposeController6: 81,
    generalPurposeController7: 82,
    generalPurposeController8: 83,
    portamentoControl: 84,
    reverbDepth: 91,
    tremoloDepth: 92,
    chorusDepth: 93,
    detuneDepth: 94,
    phaserDepth: 95,
    dataIncrement: 96,
    dataDecrement: 97,
    NRPNLsb: 98,
    NRPNMsb: 99,
    RPNLsb: 100,
    RPNMsb: 101,
    allSoundOff: 120,
    resetAllControllers: 121,
    localControlOnOff: 122,
    allNotesOff: 123,
    omniModeOff: 124,
    omniModeOn: 125,
    monoModeOn: 126,
    polyModeOn: 127
} as const;

export type midiControllers =
    (typeof midiControllers)[keyof typeof midiControllers];

export const RMIDINFOChunks = {
    name: "INAM",
    album: "IPRD",
    album2: "IALB",
    artist: "IART",
    genre: "IGNR",
    picture: "IPIC",
    copyright: "ICOP",
    creationDate: "ICRD",
    comment: "ICMT",
    engineer: "IENG",
    software: "ISFT",
    encoding: "IENC",
    midiEncoding: "MENC",
    bankOffset: "DBNK"
} as const;

export type RMIDINFOChunks =
    (typeof RMIDINFOChunks)[keyof typeof RMIDINFOChunks];
